################################################################################
# DCAT Dataset Creator Mapping (DCAT-AP-NL 3.0 compliant)
################################################################################

### Scope
scope.json = $..metadataBlocks.citation.fields[?(@.typeName=='author')].value[*]

### Subject IRI
# Names might collide, and It doesn't look nice
# So not create iri's on the fly, instead it makes them into blank nodes
# But I we want to have them; we can create an iri with the name as seen below
#subject.iri.json   = $.authorName.value
#subject.iri.format = _creator_${value}

# Name
# Mandatory
props.name.predicate       = foaf:name
props.name.as              = literal
props.name.json            = $.authorName.value

props.identifier.predicate = dct:identifier
props.identifier.as        = literal
props.identifier.json      = $.authorIdentifier.value
# Note that sometimes the identifier is just a code and not a full URI
# can we filter if it start with http(s):// and only then use it as an identifier, otherwise ignore it?
