
################################################################################
# DCAT Catalog Mapping (DCAT-AP-NL 3.0 compliant)
# Adds dct:creator; removes misuse of dct:type on publisher; keeps vCard contact.
################################################################################

### Subject IRI
# This would be the IRI of the catalog itself, which should be a resolvable URL in a real deployment. 
# The ODISSEI Portal.
subject.iri.const = https://portal.odissei.nl/

### Title (English)
props.title_en.predicate = dct:title
props.title_en.as        = literal
props.title_en.lang      = en
props.title_en.json      = $.datasetORE['ore:describes']['schema:isPartOf']['schema:name']

### Description (English)
props.description_en.predicate = dct:description
props.description_en.as        = literal
props.description_en.lang      = en
props.description_en.json      = $.datasetORE['ore:describes']['schema:isPartOf']['schema:description']

### Contact Point (vCard)
# DANS
# But maybe we make it archive specific
nodes.contact.kind                  = bnode
nodes.contact.type                  = vcard:Kind
nodes.contact.props.fn_en.predicate = vcard:fn
nodes.contact.props.fn_en.as        = literal
nodes.contact.props.fn_en.lang      = en
nodes.contact.props.fn_en.const     = Data Archiving Networked Services (DANS)
nodes.contact.props.email.predicate = vcard:hasEmail
nodes.contact.props.email.as        = iri
nodes.contact.props.email.const     = mailto:info@dans.knaw.nl
nodes.contact.props.url.predicate   = vcard:hasURL
nodes.contact.props.url.as          = iri
nodes.contact.props.url.const       = https://dans.knaw.nl/en/contact/
props.contactPoint.predicate        = dcat:contactPoint
props.contactPoint.as               = node-ref
props.contactPoint.node             = contact

### Publisher (FOAF Agent)
# DANS, can we use the ror id for all those agents ? https://ror.org/008pnp284
#nodes.publisher.kind      = bnode
nodes.publisher.kind      = iri
nodes.publisher.type      = foaf:Agent
nodes.publisher.iri.const = https://ror.org/008pnp284
nodes.publisher.props.name_en.predicate = foaf:name
nodes.publisher.props.name_en.as        = literal
nodes.publisher.props.name_en.lang      = en
nodes.publisher.props.name_en.const     = Data Archiving Networked Services (DANS)
props.publisher.predicate = dct:publisher
props.publisher.as        = node-ref
props.publisher.node      = publisher

### Creator (FOAF Agent) ? required by NL SHACL
# DANS
#nodes.creator.kind      = bnode
#nodes.creator.type      = foaf:Agent
nodes.creator.kind      = iri
nodes.creator.type      = foaf:Agent
nodes.creator.iri.const = https://ror.org/008pnp284
nodes.creator.props.name_en.predicate = foaf:name
nodes.creator.props.name_en.as        = literal
nodes.creator.props.name_en.lang      = en
nodes.creator.props.name_en.const     = Data Archiving Networked Services (DANS)
props.creator.predicate = dct:creator
props.creator.as        = node-ref
props.creator.node      = creator
