################################################################################
# DCAT Catalog Mapping (DCAT-AP-NL 3.0 compliant)
################################################################################

### Subject IRI
# This would be the IRI of the catalog itself, which should be a resolvable URL in a real deployment. 
# The ODISSEI Portal.
subject.iri.const = https://portal.odissei.nl/

### Title (English)
props.title_en.predicate = dct:title
props.title_en.as        = literal
props.title_en.lang      = en
props.title_en.json      = $.datasetORE['ore:describes']['schema:isPartOf']['schema:name']

### Description (English)
props.description_en.predicate = dct:description
props.description_en.as        = literal
props.description_en.lang      = en
props.description_en.json      = $.datasetORE['ore:describes']['schema:isPartOf']['schema:description']

### Contact Point (vCard)
# DANS
# But maybe we make it archive specific
# nodes.contact.kind                  = bnode
# nodes.contact.type                  = vcard:Kind
# nodes.contact.props.fn_en.predicate = vcard:fn
# nodes.contact.props.fn_en.as        = literal
# nodes.contact.props.fn_en.lang      = en
# nodes.contact.props.fn_en.const     = Data Archiving Networked Services (DANS)
# nodes.contact.props.email.predicate = vcard:hasEmail
# nodes.contact.props.email.as        = iri
# nodes.contact.props.email.const     = mailto:info@dans.knaw.nl
# nodes.contact.props.url.predicate   = vcard:hasURL
# nodes.contact.props.url.as          = iri
# nodes.contact.props.url.const       = https://dans.knaw.nl/en/contact/
# props.contactPoint.predicate        = dcat:contactPoint
# props.contactPoint.as               = node-ref
# props.contactPoint.node             = contact
#
# ODISSEI, fixed contact point
# ODISSEI Consortium ROR is https://ror.org/03m8v6t10
nodes.contact.kind                  = bnode
nodes.contact.type                  = vcard:Kind
nodes.contact.props.fn_en.predicate = vcard:fn
nodes.contact.props.fn_en.as        = literal
nodes.contact.props.fn_en.lang      = en
nodes.contact.props.fn_en.const     = Open Data Infrastructure for Social Science and Economic Innovations
nodes.contact.props.email.predicate = vcard:hasEmail
nodes.contact.props.email.as        = iri
nodes.contact.props.email.const     = mailto:portal@odissei.nl
nodes.contact.props.url.predicate   = vcard:hasURL
nodes.contact.props.url.as          = iri
nodes.contact.props.url.const       = https://odissei-data.nl/
nodes.contact.props.organization-name.predicate = vcard:organization-name
nodes.contact.props.organization-name.as        = literal
nodes.contact.props.organization-name.lang      = en
nodes.contact.props.organization-name.const     = ODISSEI
nodes.contact.props.identifier.predicate = dct:identifier
nodes.contact.props.identifier.as        = iri
nodes.contact.props.identifier.const     = https://ror.org/03m8v6t10
props.contactPoint.predicate        = dcat:contactPoint
props.contactPoint.as               = node-ref
props.contactPoint.node             = contact

### Publisher
# ODISSEI
nodes.publisher.kind      = iri
nodes.publisher.iri.const = https://ror.org/03m8v6t10
props.publisher.predicate = dct:publisher
props.publisher.as        = node-ref
props.publisher.node      = publisher

### Creator
# ODISSEI
nodes.creator.kind      = iri
nodes.creator.iri.const = https://ror.org/03m8v6t10
props.creator.predicate = dct:creator
props.creator.as        = node-ref
props.creator.node      = creator
