
################################################################################
# DCAT Catalog Mapping (DCAT-AP-NL 3.0 compliant)
################################################################################

### Subject IRI
# This would be the IRI of the catalog itself, which should be a resolvable URL in a real deployment. 
# The ODISSEI Portal.
subject.iri.const = https://portal.odissei.nl/

### Title (English)
props.title_en.predicate = dct:title
props.title_en.as        = literal
props.title_en.lang      = en
props.title_en.json      = $.datasetORE['ore:describes']['schema:isPartOf']['schema:name']

### Description (English)
props.description_en.predicate = dct:description
props.description_en.as        = literal
props.description_en.lang      = en
props.description_en.json      = $.datasetORE['ore:describes']['schema:isPartOf']['schema:description']

### Contact Point (vCard)
# DANS
# But maybe we make it archive specific
nodes.contact.kind                  = bnode
nodes.contact.type                  = vcard:Kind
nodes.contact.props.fn_en.predicate = vcard:fn
nodes.contact.props.fn_en.as        = literal
nodes.contact.props.fn_en.lang      = en
nodes.contact.props.fn_en.const     = Data Archiving Networked Services (DANS)
nodes.contact.props.email.predicate = vcard:hasEmail
nodes.contact.props.email.as        = iri
nodes.contact.props.email.const     = mailto:info@dans.knaw.nl
nodes.contact.props.url.predicate   = vcard:hasURL
nodes.contact.props.url.as          = iri
nodes.contact.props.url.const       = https://dans.knaw.nl/en/contact/
props.contactPoint.predicate        = dcat:contactPoint
props.contactPoint.as               = node-ref
props.contactPoint.node             = contact

### Publisher
# DANS, can we use the ror id for all those agents ? https://ror.org/008pnp284
nodes.publisher.kind      = iri
nodes.publisher.iri.const = https://ror.org/008pnp284
props.publisher.predicate = dct:publisher
props.publisher.as        = node-ref
props.publisher.node      = publisher

### Creator
# DANS
nodes.creator.kind      = iri
nodes.creator.iri.const = https://ror.org/008pnp284
props.creator.predicate = dct:creator
props.creator.as        = node-ref
props.creator.node      = creator
