################################################################################
# DCAT DataService Mapping (DCAT-AP-NL 3.0 compliant)
################################################################################

### Subject IRI
# localhost is unreachable, it would be archive specific also
#
# Use the ODISSEI Portal API
# Note that there is an OpenAPI specification at https://portal.odissei.nl//openapi
# As example we can get https://portal.odissei.nl/api/info/apiTermsOfUse
subject.iri.const = https://portal.odissei.nl/api/

### Title & Description
props.title.predicate       = dct:title
props.title.as              = literal
props.title.lang            = en
props.title.const           = Dataverse API

props.description.predicate = dct:description
props.description.as        = literal
props.description.lang      = en
# Note that the ODISSEI portal does not provide access to the files!
props.description.const     = REST API providing access to dataset metadata and services.

### Identifier
props.identifier.predicate = dct:identifier
props.identifier.as        = literal
props.identifier.const     = https://portal.odissei.nl/api/

# NOTE that https://portal.odissei.nl/api/ does not resolve, its just the base URL for the API.
### Endpoint URL (typed resource)
nodes.endpoint.kind      = iri
nodes.endpoint.type      = rdfs:Resource
nodes.endpoint.iri.const = https://portal.odissei.nl/api/
props.endpointURL.predicate = dcat:endpointURL
props.endpointURL.as        = node-ref
props.endpointURL.node      = endpoint

### Endpoint Description - documentation page, (typed rdfs:Resource per DCAT v3)
nodes.endpointDesc.kind      = iri
# could also link to the human readable documentation
#nodes.endpointDesc.iri.const = https://guides.dataverse.org/en/latest/api/native-api.html
nodes.endpointDesc.iri.const = https://portal.odissei.nl/openapi
props.endpointDescription.predicate = dcat:endpointDescription
props.endpointDescription.as        = node-ref
props.endpointDescription.node      = endpointDesc

### Language (ENG)
props.language.predicate = dct:language
props.language.const = http://publications.europa.eu/resource/authority/language/ENG
props.language.as        = iri

### Keywords
props.keyword_en.predicate = dcat:keyword
props.keyword_en.as        = literal
props.keyword_en.lang      = en
props.keyword_en.multi     = true
props.keyword_en.const     = API,Dataverse

### Access Rights 
props.accessRights.predicate = dct:accessRights
props.accessRights.const     = http://publications.europa.eu/resource/authority/access-right/PUBLIC
props.accessRights.as        = iri


### Theme (SKOS Concept)
# Not sure why a service has a Theme?
props.theme.predicate = dcat:theme
props.theme.const     = http://publications.europa.eu/resource/authority/data-theme/TECH
props.theme.as        = iri

### License 
props.license.predicate = dct:license
props.license.const     = https://creativecommons.org/publicdomain/zero/1.0/
props.license.as        = iri

### Copied the following from the catalog, it should be DANS specific

### Contact Point (vCard)
# DANS
# But maybe we make it archive specific
nodes.contact.kind                  = bnode
# No IRI, it is slightly different for the API?
nodes.contact.type                  = vcard:Kind
nodes.contact.props.fn_en.predicate = vcard:fn
nodes.contact.props.fn_en.as        = literal
nodes.contact.props.fn_en.lang      = en
nodes.contact.props.fn_en.const     = Open Data Infrastructure for Social Science and Economic Innovations
nodes.contact.props.email.predicate = vcard:hasEmail
nodes.contact.props.email.as        = iri
nodes.contact.props.email.const     = mailto:portal@odissei.nl
nodes.contact.props.url.predicate   = vcard:hasURL
nodes.contact.props.url.as          = iri
nodes.contact.props.url.const       = https://odissei-data.nl/
props.contactPoint.predicate        = dcat:contactPoint
props.contactPoint.as               = node-ref
props.contactPoint.node             = contact

### Publisher 
# ODISSEI
nodes.publisher.kind      = iri
nodes.publisher.iri.const = https://ror.org/03m8v6t10
props.publisher.predicate = dct:publisher
props.publisher.as        = node-ref
props.publisher.node      = publisher

### Creator
# IQSS or otherwise the Dataverse.org team, but for now I will ignore it
# nodes.creator.kind      = iri
# nodes.creator.iri.const = https://ror.org/03m8v6t10
# props.creator.predicate = dct:creator
# props.creator.as        = node-ref
# props.creator.node      = creator
